/// Flutter icons FrontendIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FrontendIcons
///      fonts:
///       - asset: fonts/FrontendIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FrontendIcons {
  FrontendIcons._();

  static const _kFontFam = 'FrontendIcons';
  static const String? _kFontPkg = null;

  static const IconData fingerprint_stroke = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insights = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go_stroke = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
